### ISSUE TITLE
Can't start a new meeting

### ISSUE THREAD

**Issue by obedparla** [chaifeng/alfred-zoomus#3]
Hey! I love the workflow. 

However, I can't seem to get the `start a new meeting` workflow working. I type `zm` and then press `cmd + return` but nothing happens. 

Am I doing something wrong?

**Comment by chaifeng** [comment]
Fixed it! The new version v3.3 is released.

Thanks!

**Comment by obedparla** [comment]
Thank you @chaifeng ! I tried the new version but it still doesn't create a new Zoom meeting when pressing `zm + cmd`. It just opens Zoom. I'm logged in with it and using Version: 4.4.6

**Comment by chaifeng** [comment]
It happens when Zoom is launched by this workflow, right? I forgot to test this scenario.

Please upgrade to the version v3.3.1
